version: "3"

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - SQL_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bingobongo